services:
  - type: web
    name: turnitin-downloader
    env: node
    plan: free
    region: oregon # O tu región preferida
    # Especificar una versión LTS de Node.js muy estable
    # Render puede estar usando una versión demasiado nueva por defecto para el runtime.
    nodeVersion: "20.12.2" # O la última LTS, ej: "18.19.1"
    buildCommand: npm install --omit=dev && npm run build # --omit=dev para no instalar puppeteer
    startCommand: node dist/app.js # Comando de inicio correcto
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: LOCAL_WORKER_URL # <--- AÑADIR ESTA VARIABLE
        value: "https://TU_URL_DE_NGROK.ngrok.io" # Reemplaza esto con tu URL real de ngrok
