services:
  - type: web
    name: turnitin-downloader
    env: node
    plan: free
    region: oregon # O tu región preferida
    # Especificar una versión LTS de Node.js muy estable
    # Render puede estar usando una versión demasiado nueva por defecto para el runtime.
    nodeVersion: "20.12.2" # O la última LTS, ej: "18.19.1"
    buildCommand: npm install && npm run build
    startCommand: node dist/app.js # Comando de inicio correcto
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_ARGS
        value: "--no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--no-first-run,--disable-extensions,--disable-gpu"
      - key: PORT
        value: 10000
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
